### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by V39Pygamer** [vismodo/Python-Quiz-Application#1]
it is giving me an error invalid syntax when I try to run it

**Comment by vismodo** [comment]
Which Line?

**Comment by vismodo** [comment]
Yes. I forgot to end the tkinter widget on the 90th line. It was an EOF error.

https://github.com/vismodo/Python-Quiz-Application/blob/6a23e23775c4d956ba7370eba616e4fdf69abc0e/PyQuiz.py#L90

It seems to be fixed. I am closing this issue. Let me know if there is anything else.
